PLAY_PAUSE_KEY = ' '
NEXT_SONG_KEY = 'A'
PREVIOUS_SONG_KEY = 'B'

NEXT_PLAYLIST_KEY = 'C'
PREVIOUS_PLAYLIST_KEY = 'D'

RANDOM_SONG_IN_PLAYLIST_KEY = 'E'
RANDOM_SONG_ANYWHERE_KEY = 'F'

TOGGLE_EXCLUDED_GENRES_KEY = 'G'

QUIT_KEY = 'Q'
SHUTDOWN_KEY = 'Z'
